apiVersion: v1
kind: Service
metadata:
     name: phpapp-service
spec:
     selector:
          app: phpapp
     ports:
          - protocol: TCP
            port: 8080
            targetPort: 80
     type: NodePort
